name: Docker Build & Push

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "src/**"
      - "Dockerfile"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Echo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Ghcr Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: cdsctf
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define tags
        id: meta
        run: |
          set -e

          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGES=(
            "ghcr.io/${REPO_OWNER}/echo"
          )

          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TAGS=("latest" "${SHORT_SHA}")

          COMBINED_TAGS=()
          for img in "${IMAGES[@]}"; do
            for tag in "${TAGS[@]}"; do
              COMBINED_TAGS+=("${img}:${tag}")
            done
          done

          OUTPUT=$(IFS=, ; echo "${COMBINED_TAGS[*]}")
          echo "tags=$OUTPUT" >> $GITHUB_OUTPUT
          echo "$OUTPUT"

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.title=echo
            org.opencontainers.image.version=${{ steps.current.outputs.version }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
